services:
  # PostgreSQL para Evolution API
  evolution-db:
    image: postgres:latest
    container_name: evolution-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pwd159753
      POSTGRES_DB: postgres_db
    expose:
      - "5432"
    volumes:
      - evolution_pgdata:/var/lib/postgresql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d postgres_db"]
      interval: 30s
      timeout: 5s
      retries: 5

  # Redis para Evolution API
  redis:
    image: redis:latest
    container_name: evolution-redis
    command: ["redis-server", "--requirepass", "pwd159753"]
    restart: always
    expose:
      - "6379"
    volumes:
      - evolution_redisdata:/data
    networks:
      - app-network

  # Evolution API
  evolution:
    image: evoapicloud/evolution-api:latest
    container_name: evolution-api
    restart: always
    environment:
      AUTHENTICATION_API_KEY: pwd159753
      DATABASE_PROVIDER: postgresql
      DATABASE_CONNECTION_URI: postgresql://admin:pwd159753@evolution-db:5432/postgres_db
      CACHE_REDIS_URI: redis://default:pwd159753@redis:6379
    volumes:
      - ./evolution_instances:/evolution/instances
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      evolution-db:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  
  # Evolution API volumes
  evolution_pgdata:
    driver: local
  evolution_redisdata:
    driver: local

networks:
  app-network:
    driver: bridge